import { Product } from './Dashboard.interface'

export const fetchProducts = async (): Promise<Product[]> => {
  // Replace with real API fetch if needed:
  return [
    {
      refPtId: 101,
      refCategoryId: 24,
      refSubCategoryId: 1,
      poDescription: 'Traditional pink silk pattu pavadai for kids',
      poDisc: '150.00',
      poDiscPercent: '10',
      poHSN: '6204',
      poId: 1,
      poPrice: '1500.00',
      poQuantity: '10',
      poSKU: 'S-PATTU-001',
      poTotalPrice: '1350.00',
      poName: 'Red Kanjeevaram Silk Saree',
      updatedAt: new Date().toISOString(),
      updatedBy: 'admin',
      createdAt: new Date().toISOString(),
      createdBy: 'admin',
      isDelete: false
    },
    {
      refPtId: 101,
      refCategoryId: 24,
      refSubCategoryId: 1,
      poDescription: 'Traditional pink silk pattu pavadai for kids',
      poDisc: '150.00',
      poDiscPercent: '10',
      poHSN: '6204',
      poId: 1,
      poPrice: '1500.00',
      poQuantity: '10',
      poSKU: 'S-PATTU-001',
      poTotalPrice: '1350.00',
      poName: 'Red Kanjeevaram Silk Saree',
      updatedAt: new Date().toISOString(),
      updatedBy: 'admin',
      createdAt: new Date().toISOString(),
      createdBy: 'admin',
      isDelete: false
    },
    {
      refPtId: 101,
      refCategoryId: 24,
      refSubCategoryId: 1,
      poDescription: 'Traditional pink silk pattu pavadai for kids',
      poDisc: '150.00',
      poDiscPercent: '10',
      poHSN: '6204',
      poId: 1,
      poPrice: '1500.00',
      poQuantity: '10',
      poSKU: 'S-PATTU-001',
      poTotalPrice: '1350.00',
      poName: 'Red Kanjeevaram Silk Saree',
      updatedAt: new Date().toISOString(),
      updatedBy: 'admin',
      createdAt: new Date().toISOString(),
      createdBy: 'admin',
      isDelete: false
    },
    {
      refPtId: 101,
      refCategoryId: 24,
      refSubCategoryId: 1,
      poDescription: 'Traditional pink silk pattu pavadai for kids',
      poDisc: '150.00',
      poDiscPercent: '10',
      poHSN: '6204',
      poId: 1,
      poPrice: '1500.00',
      poQuantity: '10',
      poSKU: 'S-PATTU-001',
      poTotalPrice: '1350.00',
      poName: 'Red Kanjeevaram Silk Saree',
      updatedAt: new Date().toISOString(),
      updatedBy: 'admin',
      createdAt: new Date().toISOString(),
      createdBy: 'admin',
      isDelete: false
    },
    {
      refPtId: 101,
      refCategoryId: 24,
      refSubCategoryId: 1,
      poDescription: 'Traditional pink silk pattu pavadai for kids',
      poDisc: '150.00',
      poDiscPercent: '10',
      poHSN: '6204',
      poId: 1,
      poPrice: '1500.00',
      poQuantity: '10',
      poSKU: 'S-PATTU-001',
      poTotalPrice: '1350.00',
      poName: 'Red Kanjeevaram Silk Saree',
      updatedAt: new Date().toISOString(),
      updatedBy: 'admin',
      createdAt: new Date().toISOString(),
      createdBy: 'admin',
      isDelete: false
    },
    {
      refPtId: 101,
      refCategoryId: 24,
      refSubCategoryId: 1,
      poDescription: 'Traditional pink silk pattu pavadai for kids',
      poDisc: '150.00',
      poDiscPercent: '10',
      poHSN: '6204',
      poId: 1,
      poPrice: '1500.00',
      poQuantity: '10',
      poSKU: 'S-PATTU-001',
      poTotalPrice: '1350.00',
      poName: 'Red Kanjeevaram Silk Saree',
      updatedAt: new Date().toISOString(),
      updatedBy: 'admin',
      createdAt: new Date().toISOString(),
      createdBy: 'admin',
      isDelete: false
    },
    {
      refPtId: 101,
      refCategoryId: 24,
      refSubCategoryId: 1,
      poDescription: 'Traditional pink silk pattu pavadai for kids',
      poDisc: '150.00',
      poDiscPercent: '10',
      poHSN: '6204',
      poId: 1,
      poPrice: '1500.00',
      poQuantity: '10',
      poSKU: 'S-PATTU-001',
      poTotalPrice: '1350.00',
      poName: 'Red Kanjeevaram Silk Saree',
      updatedAt: new Date().toISOString(),
      updatedBy: 'admin',
      createdAt: new Date().toISOString(),
      createdBy: 'admin',
      isDelete: false
    },
    
  ]
}
